name: Documentation Issue Template
description: An Issue Template for Documentations
title: '[Documentation] '
labels: ['documentation']
assignees: []
body:
  - type: textarea
    attributes:
      label: Description
      description: Describe the documentation
      placeholder: Describe the documentation
    validations:
      required: true
  - type: textarea
    attributes:
      label: Todos
      description: List of todos
      placeholder: |
        - [ ] Todo 1
        - [ ] Todo 2
        - [ ] Todo 3
      value: |
        - [ ]
    validations:
      required: false
