name: Build & Deploy Staging

on:
  push:
    branches:
      - master

jobs:
  build:
    uses: gsainfoteam/infoteam-actions/.github/workflows/default-docker-build.yml@master
    with:
      repo_name: ziggle-backend
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs:
      - build

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: gsainfoteam/infoteam-infra
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          fetch-depth: 0

      - name: Set version ENV, and commit
        run: |
          VERSIONS_FILE_PATH=apps/mail/ziggle-backend-stg/versions.env

          source $VERSIONS_FILE_PATH
          BACKEND_TAG="${GITHUB_REF_NAME}_${GITHUB_SHA}"
          cat <<EOF > $VERSIONS_FILE_PATH
          BACKEND_TAG="${BACKEND_TAG}"
          EOF
          git config --local user.email "github-actions+ziggle_be@servers.gistory.me"
          git config --local user.name "Github-Actions[bot] @ gsainfoteam/ziggle_be"
          git commit -a -m "mail/ziggle-backend-stg: update version.env to ${GITHUB_SHA::7}"
      - name: Push to infoteam-infra
        uses: ad-m/github-push-action@master
        with:
          ssh: true
          repository: gsainfoteam/infoteam-infra
          branch: master
