name: Update Kubernetes Cluster (Dev)

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build docker Image
    runs-on: ubuntu-latest
    outputs:
      ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      ECR_REPOSITORY: ziggle-backend
      IMAGE_TAG: dev${{ github.run_number }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2
          mask-aws-account-id: no

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build, tag, and push image to Amazon ECR
        uses: docker/build-push-action@v2
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ziggle-backend
          IMAGE_TAG: dev${{ github.run_number }} # Use run number as image tag
        with:
          context: .
          push: true
          tags: ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    name: Update Git Repository
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          repository: gsainfoteam/icarus-gitops
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          fetch-depth: 0

      - name: Update Kubernetes Manifest
        env:
          ECR_REGISTRY: ${{ needs.build.outputs.ECR_REGISTRY }}
          ECR_REPOSITORY: ${{ needs.build.outputs.ECR_REPOSITORY }}
          IMAGE_TAG: ${{ needs.build.outputs.IMAGE_TAG }}
        run: |
          cd icarus-gitops/infoteam/service/ziggle
          sed -i "s|image:.*|image: $ECR_REGISTRY\/$ECR_REPOSITORY:$IMAGE_TAG|g" stg.yaml

      - name: Commit and Push
        run: |
          cd icarus-gitops
          git config --global user.email "psw041115@gmail.com"
          git config --global user.name "siwonpada"
          git commit -am "Update image $ECR_REPOSITORY tag $IMAGE_TAG"
          git push -u origin master
